#!/bin/bash

TARGET=/etc/crontab
BACKUP=/etc/.crontab_backup

if [ ! -e $BACKUP ]; then
   echo "Backup does not exist"
   sudo cp $TARGET $BACKUP
   exit 0
fi

MD5=`md5sum $TARGET | awk '{ print $1 }'`
MD5_BACKUP=`md5sum $BACKUP | awk '{ print $1 }'`

if [ -z $MD5 ] | [ -z $MD5_BACKUP ]; then
   echo "MD5 is empty."
fi

if [ "$MD5" != "$MD5_BACKUP" ]; then
   echo "Crontab has been modified" | mail -s "Report" root
fi

sudo cp $TARGET $BACKUP

#we have to set up the scheduling by running the command "crontab -e"
#and add "0 0 * * *  <this .sh file's path>" to make it run every night 0:00
#source for if else: http://www.dreamsyssoft.com/unix-shell-scripting/ifelse-tutorial.php
#source for cut: https://stackoverflow.com/questions/816820/use-space-as-a-delimiter-with-cut-command
#and man mail